name: yylab-fields

services:
  nginx:
    image: tiangolo/nginx-rtmp:latest-2024-09-16
    ports:
      - '8888:8888'
      - '21935:1935'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static/public:/var/www/static:ro

  postgres:
    image: postgres:16.4-bookworm
    environment:
      POSTGRES_USER: "${DOCKER_POSTGRES_USER:-pguser}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD:-fields-pg-password}"
      POSTGRES_DB: fields
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-bookworm
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
