services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: armkn-proficiv-nginx
    env_file: ./nginx.env
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./backend/static:/var/www/static
