name: yylab-fields

services:
  nginx:
    image: tiangolo/nginx-rtmp:latest-2023-11-13
    ports:
      - "8080:80"
      - "21935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/static/public:/var/www/static
    extra_hosts:
      # コンテナ内部からコンテナ外のネイティブのホストへ繋げるようにする
      # `host-gateway` が特殊なキーワードで，`native-host` は任意のドメイン名にできる
      - native-host:host-gateway

  postgres:
    image: postgres:16.0-bookworm
    env_file: ./.env.postgres
    environment:
      #POSTGRES_USER: See .env.postgres
      #POSTGRES_PASSWORD: See .env.postgres
      POSTGRES_DB: fields
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-bookworm
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
