sequenceDiagram
  participant C as Client (WebBrowser)
  participant A as API Server
  participant Q as Job Queue
  participant W as Worker
  participant D as DB
  participant S as Sensor


  C->>A: POST /recording/start
  activate C
  A->>C: 200 OK {"record_id": 1234}
  A->>S: 収録開始

  C->>A: POST /recording/end
  deactivate C

  A->>S: 収録終了
  A->>Q: 収録評価ジョブ追加
  W->>Q: ジョブ取り出し・遂行
  activate W

  C->>A: GET /records/1234 <br/>(熟練度の評価結果取得)
  A->>D: 収録の評価読み出し
  A->>C: 200 OK {"status": "processing"}

  W->>D: ジョブの評価を保存
  deactivate W

  C->>A: GET /records/1234 <br/>(熟練度の評価結果取得)
  A->>D: 収録の評価読み出し
  A->>C: 200 OK {"status": "done", "segs": [...]}
